export const STRINGS = {
    paycheck: 'תלוש שכר',
    'opening a bank account': 'פתיחת חשבון בנק',
    'making income': 'יצירת הכנסות',
    saving: 'חיסכון',
    investments: 'השקעות',
    'employment rights': 'זכויות עובד',
    subjectsScreenTitle: 'אז במה מתמקדים היום?',
    learningStylesScreenTitle: 'באיזו דרך?',
    readingStyleScreenTitle: 'לקרוא על {0}',
    gamingStyleScreenTitle: 'להתנסות ב{0}',
    watchingStyleScreenTitle: 'לצפות ב{0}',
    listeningStyleScreenTitle: 'להקשיב ל{0}',
    quizScreenTitle: 'חידון {0}',
    read: 'לקרוא',
    watch: 'לצפות',
    listen: 'להקשיב',
    play: 'להתנסות',
    minutes: "דק'",
    missingDataErrorMessage: 'משהו השתבש...',
    test: 'בדיקה',
    next: 'הבא',
    finish: 'סיים',
    'No Units For Now': 'אין יחידות לימוד להציג',
    "What's Missing?": 'מה חסר?',
    'Find the Error': 'חפש את התעות',
    'Paycheck Structure Explanation': 'הסבר על מבנה התלוש',
    "Paycheck Day Arrived. What's next?": 'הגיע התלוש. מה עושים עכשיו?',
    'What to do if the Paycheck is Broken?': 'מה עושים אם התלוש תקול?',
    'Missing Video Source': 'מקור וידאו חסר',
    'The meaning of each section': 'המשמעות של כל סעיף',
    '10 tips for quick review': '10 טיפים למעבר מהיר',
    'Issues in the paycheck and how to handle it': 'בעיות בתלוש ואיך להתמודד',
    'The Big Quiz': 'החידון הגדול',
    '10 trivia questions about your paycheck': '10 שאלות טריוויה על תלוש שכר',
    'Not here.. in the paycheck!': 'לא כאן.. בתלוש!',
    'Except your employee bonus': 'חוץ מהבונוס שלך לעובד/ת החודש',
    'Try again': 'נסה שוב 😬',
} as const;

export type StringKey = keyof typeof STRINGS;
