name: Staging Publish
on:
    push:
        branches: -staging
        
    workflow_dispatch:

jobs:
    update:
        name: EAS Update
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: npm install

            - name: Build
              run: eas build --profile preview --platform android --non-interactive
